### ISSUE TITLE
Subscriptions may get invoked before router is created

### ISSUE THREAD

**Issue by aknuds1** [yoshuawuyts/choo#420] opened 2017-03-01 16:28 UTC
Model subscriptions may get invoked by Choo at a stage where Choo hasn't yet created its router, as a result of [calling _store.start](https://github.com/yoshuawuyts/choo/blob/master/index.js#L65). This can lead to havoc in that subscriptions may trigger rendering, which again depends on the internal router reference.  When the internal router is null in this case, a bug occurs.

Is this down to a bug in Choo, i.e. that subscriptions might get invoked before the router is instantiated? Seems that way to me, but I can't tell for sure.

**Comment by yoshuawuyts** [comment] 2017-03-02 00:01
Yeah, looks like a regression - we should enforce subscriptions only get
loaded on the next tick. This can be done by initializing barracks without
subs enabled (like in
https://github.com/yoshuawuyts/choo/blob/master/index.js#L47) and then
turning them on later

**Comment by aknuds1** [comment] 2017-03-02 00:18
Thanks @yoshuawuyts. Should I try to come up with a PR for this issue?

**Comment by yoshuawuyts** [comment] 2017-03-21 02:55
In choo v5 there's the `DOMContentLoaded` event - I think that should mitigate this.

---
Closing because `choo@5` will introduce a new API. See #425 for the merged PR. Thanks!

**Closed by yoshuawuyts** 2017-03-21 02:55 UTC
