### ISSUE TITLE
setLocation does not update history pushstate

### ISSUE THREAD

**Issue by jondashkyle** [yoshuawuyts/choo#158] opened 2016-07-12 01:02 UTC
### Expected behavior
When using `setLocation` to programmatically navigate, the history state should update as though clicking an internal link. Additionally, when manually calling `history.pushState` sheet-router does not update.

### Actual behavior
Choo retains the path of the route where `setLocation` was called.

### Steps to reproduce behavior
`send('location:setLocation', { location: '/' })` 

Just wondering if this is the intended behavior? I can see it going either way. As noted in the docs, prob not best practice to use this all over the place, but in my (odd) situation it seems useful.

**Comment by yoshuawuyts** [comment] 2016-07-12 12:22
Yeah, you're right - this is def a bug we need to address. Duplicate of #85 tho; going to close this issue so we can continue the convo there :sparkles:

**Closed by yoshuawuyts** 2016-07-12 12:22 UTC
Labels: bug, duplicate
