### ISSUE TITLE
Subscriptions never get called?

### ISSUE THREAD

**Issue by crapthings** [yoshuawuyts/choo#107] opened 2016-07-01 04:32 UTC
i just put a log inside subscription, but nothing happen.

    const horizon = Horizon()

    const choo = require('choo')
    const app = choo()

    const form2js = require('form2js').form2js

    const person = horizon('person')

    app.model({
      namespace: 'app',
      state: {
        title: 'Set the title'
      },
      reducers: {
        update: (action, state) => ({
          title: action.value
        }),

        submit: (action, state) => {
          console.log(action, state)
        }
      },
      subscriptions: [
        (send) => setInterval(() => {
          console.log(1)
        }, 1000)
      ]
    })

    const personFormView = (params, state, send) => {
      return choo.view`
        <form id='personForm' onsubmit=${submit}>
          <input type='text' name='name' autofocus />
          <input type='submit' value='submit' />
        </form>
      `

      function submit (e) {
        e.preventDefault()
        let data = form2js(e.currentTarget.id)
        send('app:submit', data)
      }
    }

    const mainView = (params, state, send) => choo.view `
      <div>
        ${personFormView(params, state, send)}
      </div>
    `

    app.router((route) => [
      route('/', mainView)
    ])

    horizon.onReady(function () {
      document.querySelector('h1').innerHTML = 'horizon_testfield works!'
      const tree = app.start()
      document.body.appendChild(tree)
    })

    horizon.connect()

**Comment by bendrucker** [comment] 2016-07-01 05:54
Subscriptions are only called from the browser when the `DOMContentLoaded` event fires on the document.

**Comment by crapthings** [comment] 2016-07-01 06:23
my entry html is like

    <!doctype html>
    <html>

    <head>
        <meta charset="UTF-8">
        <script src="/horizon/horizon.js"></script>
    </head>

    <body>
        
        <h1></h1>
        <div id="app"></div>
    </body>

    <script src="./bundle.js"></script>

    </html>

i have only one file bundle.js that loaded in browser.

**Comment by crapthings** [comment] 2016-07-01 06:28
i have tried

    subscriptions: [
      send => {
        document.addEventListener("DOMContentLoaded", function (event) {
          console.log("DOM fully loaded and parsed");
        })
      }
    ]

or

    document.addEventListener("DOMContentLoaded", function (event) {
      console.log("DOM fully loaded and parsed");
      const tree = app.start()
      document.body.appendChild(tree)
    })

it doesn't work.

**Comment by yoshuawuyts** [comment] 2016-07-01 09:20
I'm not quite sure what some of the extra functions in your code are, but [here's a gist](http://requirebin.com/?gist=478cbf17fc940d172724bbbdae457ab0) of subscriptions in action. I hope it clarifies how they work.

I'm going to close this issue for now as it's not a bug in `choo` (phew!); but happy to continue discussing / assisting wherever you run into trouble. Cheers!

**Closed by yoshuawuyts** 2016-07-01 09:20 UTC
Labels: question
