### ISSUE TITLE
Feature request: Programatic navigation

### ISSUE THREAD

**Issue by josephg** [yoshuawuyts/choo#85] opened 2016-06-26 13:54 UTC
I've ended up using this action to navigate between pages:

``` javascript
  effects: {
    navigate: (action, state, send) => {
      send('app:location', {location: action.location});
      window.history.pushState({}, null, action.location);
    }
  }
```

It'd be nice if there was an officially recommended way to do it. (This or something else.)

**Comment by timwis** [comment] 2016-06-26 14:18
Hey @josephg, we were just talking about this (see #21). It looks like the best way may be to use the native DOM API (`window.location.hash = 'foo'`). For browser history, I can't member if it's `windoe.location.url` or  `pushState` as you have above. But the point is, adjusting those triggers the internal router. And the nice thing about this is that you don't have to memorize a new framework-specific way to change the page/URL. How's that sound?

**Comment by josephg** [comment] 2016-06-27 00:57
If we can pull it off, perfect. I tried that first hoping it would automatically work. Thanks!

**Comment by yoshuawuyts** [comment] 2016-06-30 14:50
@josephg Did you end up resolving this; can this be closed?

**Comment by josephg** [comment] 2016-06-30 23:02
Well if thats the intended behaviour, it doesn't work yet:

```javascript
const choo = require('choo');
const app = choo();

const nav = (url) => {
  console.log('nav to', url);
  window.history.pushState(null, null, '/foo');
}

app.router((route) => [
  route('/', (params, state, send) => choo.view`
    <button onclick=${() => nav('/foo')}>Nav</button>
  `),

  route('/foo', (params, state, send) => choo.view`<h1>Somewhere else</h1>`)
]);

document.body.appendChild(app.start());
```

... The button changes the URL but the new route isn't rendered.

**Comment by timwis** [comment] 2016-06-30 23:10
`window.location.href = '/foo'` works for me with your code

**Comment by josephg** [comment] 2016-06-30 23:18
@timwis: That forces an unnecessary full page re-render, which I'm trying to avoid.

**Comment by josephg** [comment] 2016-07-01 01:08
Also @yoshuawuyts: Taking a look at the browser's API, I don't think there's any way for the framework to find out when `pushState` / `replaceState` is called.

From [MDN](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onpopstate):
> Note that just calling history.pushState() or history.replaceState() won't trigger a popstate event. The popstate event is only triggered by doing a browser action such as clicking on the back button (or calling history.back() in JavaScript). 

So for simple navigation, `pushState` will need to be wrapped somewhere. It can happen in the app - using something like the code I posted at the top of this issue. Or it can be in choo itself.

**Comment by yoshuawuyts** [comment] 2016-07-01 22:10
@josephg you're right - labelling this a bug; we should fix this

**Comment by MattMcFarland** [comment] 2016-08-02 11:35
So what would the appropriate fix be?  

If someone changes the window.location, are you saying we need to let choo know somehow?  I would prefer that this is done manually, or at least by somehow setting up a subscription to the window.  

At anyrate, can someone explain what the problem / intended result should be?  I'm not clear on the issue, the original post actually seems like a reasonable approach to me and it doesnt look like a bug.  So I must be reading this wrong.

**Comment by mantoni** [comment] 2016-08-02 12:06
@MattMcFarland It's not a bug. It's a feature request to make it possible to change the location with a single API call (e.g. `send('app:location', {location: action.location});`) without the need to manually fiddle with pushState. Does that answer your question?

**Comment by MattMcFarland** [comment] 2016-08-02 12:14
@mantoni Yes thank you!

Is this a feature we are going to add?  If so I could work on this providing nobody else is. I"m just looking for something to do :)

**Comment by mantoni** [comment] 2016-08-02 13:25
@MattMcFarland I saw that @yoshuawuyts was looking into it recently and concluded that this would be a breaking change ([see his last comment here](https://github.com/yoshuawuyts/choo/pull/182)).

**Comment by yoshuawuyts** [comment] 2016-08-02 14:04
Just had a discussion about this with @juliangruber, and we came up with the
following for hash routing:

Inline anchor tags and hash routing cannot co-exist in the same application.
You can choose one, but hash routing should be the default. This is chosen because `choo` is primarily intended for single page apps, and using hash routing is more in line with that.

Hash routes should be explicit in the application. They're enumerable, and
dynamic hashing can be done through partials:
```js
// enumerable
app.router('/404', [
  [ '/foo', () => {} ],
  [ '/foo#bar', () => {} ],
  [ '/foo#baz', () => {} ],
])
// '/foo#baz' => OK
// '/foo#ohno' => ERROR
```

```js
// dynamic
app.router('/404', [
  [ '/foo', () => {} ],
  [ '/foo#:baz', () => {} ],
])
// '/foo#baz' => OK
// '/foo#ohno' => OK
```

An option should be available to enable anchor tag routing, through:
`{ anchors: true}`.

Browser routing updates can be disabled as a whole through the existing option
of `{ history: false }` - which is useful for widget-like situations.

Thoughts? - should this proposal perhaps be a separate issue?

**Comment by yoshuawuyts** [comment] 2016-12-12 02:09
Yup I think this should all work now in `v4` - closing! :grin:

**Closed by yoshuawuyts** 2016-12-12 02:09 UTC
Labels: bug, duplicate
