### ISSUE TITLE
Infinite loop of effect 4.0.0

### ISSUE THREAD

**Issue by dbtek** [yoshuawuyts/choo#367] opened 2016-12-16 15:45 UTC
Thanks for providing this. I really liked it and appreciate all the effort.
Sorry if I missed something. But I could not find the answer while updating to 4.0.0 / 4.0.1

### Expected behavior
Effect to be fired once.

### Actual behavior
Submitting a form by firing an effect produces infinite loop. Fired effect keeps running endlessly.

### Steps to reproduce behavior
Here an effect in model `auth`:
```js
    ...
    attemptLogin: (state, data, send, done) => {
      send('auth:setPending', true, done)
      const cred = firebase.auth.EmailAuthProvider.credential(data.email, data.password)
     // auth = firebase.auth()
      auth.signInWithCredential(cred)
        .then(res => {
          console.log('notify:info', { message: 'Successfully signed in' })
          send('auth:setPending', false, done)
        })
        .catch(error => {
          console.log('notify:error', { message: error.message }, done)
          //send('notify:error', { message: error.message }, done)
          send('auth:setPending', false, done)
          //send('auth:logout', done)
        })
```

This is from login view:
```js
const loginComponent = (state, send) => {
  const handleSubmit = (e) => {
    e.preventDefault()
    const inputs = e.target.querySelectorAll('input')
    send('auth:attemptLogin', {email: inputs[0].value, password: inputs[1].value})
  }
  ...
```

**Comment by aknuds1** [comment] 2016-12-16 15:48
Might this be similar to https://github.com/yoshuawuyts/choo/issues/363? It looks like this bug I found/fixed in nanotick.

**Comment by yoshuawuyts** [comment] 2016-12-20 00:28
This looks like a dupe of #363, the latest version of choo includes a fix - closing for now, happy tk reopen if updating doesn't resolve your issue

**Closed by yoshuawuyts** 2016-12-20 00:28 UTC
