### ISSUE TITLE
Is Choo supposed to call a route handler twice on loading the page?

### ISSUE THREAD

**Issue by aknuds1** [yoshuawuyts/choo#399] opened 2017-01-28 14:56 UTC
When loading my app, I experience that Choo calls the route handler twice in immediate succession. Any idea why this is?

It's causing some trouble, as I load data before rendering a route first, and the second render happens before the state has had time to update itself (via a reducer, which Choo invokes asynchronously). The result is that I load data for the route twice, seeing as my route handler can't tell from the state that it's already been called.

**Comment by josephluck** [comment] 2017-01-28 15:44
It'd be good to see some code for your example, but on first guess you need to be using the onload lifecycle event to send the effect to load the data, that way, when your route is called for the first time, the effect is sent and your view is rerendered when the data has loaded. Using the onload lifecycle event will prevent the effect from sending on the second render.

**Comment by aknuds1** [comment] 2017-01-28 16:15
@josephluck Hm.. I would have to reconcile that with the scenario of switching to another route in the client, where you also need to load the data first before rendering the route.

I would like to know, still, however, why it is Choo thinks it's necessary to render twice in a row without any state change (AFAICT).

**Comment by josephluck** [comment] 2017-01-29 02:53
If your switching route and loading data, you should try using the onload hook on the target route so it loads data after first render. 

In frameworks like vue, you get an API specifically for loading route data (which prevent render until the asynchronous request is returned), but these APIs are not necessary when you have a single direction data flow like react + redux, elm, choo etc.

Is it possible to see a requirebin reproduction of your case? I haven't experienced choo calling a route handler twice unnecessary in my experience so I'm intrigued :-)

**Comment by aknuds1** [comment] 2017-01-29 12:07
@josephluck So choo has an `onload` hook, is that a recent development? Wasn't aware there is one. The project in question is closed source unfortunately, but I'll see if I can figure out why choo is rendering twice and come back with more info.

**Comment by josephluck** [comment] 2017-01-29 13:25
Choo's HTML module is built upon yoyo, bel and hyperx and I believe onload and onunload are part of yoyo.

**Comment by josephluck** [comment] 2017-01-29 13:29
Actually, I stand corrected, it's built into choo, not yo-yo, as per choo's readme

**Comment by aknuds1** [comment] 2017-01-29 13:29
Thanks @josephluck, so I should add an `onunload` property to my DOM elements to benefit from this lifecycle event. I'll keep it in mind.

**Comment by josephluck** [comment] 2017-01-29 13:35
Yeah, at least that's the way I have dealt with this problem in both choo and react projects. It gives you the opportunity to render a placeholder / loading UI whilst you're waiting for the async request to finish too.

**Comment by axelav** [comment] 2017-01-30 01:01
I was having this exact issue. @josephluck your suggesting on checking out `bel`'s lifestyle hooks saved me a lot of time.

@aknuds1 here are the docs: https://github.com/shama/bel#lifecycle-events

**Comment by aknuds1** [comment] 2017-01-31 12:34
@josephluck When you say that onload should be a hook on the target route, do you actually mean it should be an attribute on a rendered DOM element? That's how I understand the [bel documentation](https://github.com/shama/bel#lifecycle-events).

I don't use bel though, and I can't see that `onload` gets invoked on my DOM elements. Is `onload` specific to bel?

**Comment by aknuds1** [comment] 2017-01-31 12:35
Yeah, to answer my own question, it's a wrapper to [on-load](https://www.npmjs.com/package/on-load) that's built into bel. @axelav @josephluck

**Comment by aknuds1** [comment] 2017-01-31 16:38
@josephluck I'm trying your suggested approach. However, it's not working since the views corresponding to different routes aren't loaded into the DOM when you switch routes, they are just diffed (or morphed) into it if you see what I mean.

The `onload` hook is only called when the app is loaded, after that it's dead in the water as I switch routes.

**Comment by aknuds1** [comment] 2017-01-31 18:01
I solved the latter by foregoing `on-load` and instead using [MutationObserver](https://developer.mozilla.org/en/docs/Web/API/MutationObserver) to detect when a new route view is inserted into the DOM, via a custom data attribute. I think this is a much more robust approach than relying on on-load.

**Comment by josephluck** [comment] 2017-02-01 01:25
I'd be interested in your routing framework.

IIRC, onload uses mutation observer under the hood to call a method when a node is added to the dom. It shouldn't only be called on app load, it should be called every time the node is added to the dom. It's the inverse for onunload. 

I did see some issues if you have the same top level node in your views. From what I can tell, morphdom doesn't treat the top level node as a change (because it's technically has not been changed despite being in another route) and consequently, onload is not called. As an interim solution, I've been adding unique id attributes on the top level node of each route. It's not the ideal solution but it kinda works. 

@yoshuawuyts - is this something choo can resolve?

**Comment by aknuds1** [comment] 2017-02-01 12:05
@josephluck I created [a repo](https://github.com/aknuds1/choo-routehandler) for it. It's in a very rough state though, I haven't done anything to make it stand alone as a package of its own! I'm also working out the kinks through experience with my own app, it's quite difficult to get it right :(

**Comment by yoshuawuyts** [comment] 2017-03-21 02:54
Closing because `choo@5` will introduce a new API. See #425 for the merged PR. Thanks!

**Closed by yoshuawuyts** 2017-03-21 02:54 UTC
