### ISSUE TITLE
http errors throwing twice?

### ISSUE THREAD

**Issue by timwis** [yoshuawuyts/choo#193] opened 2016-07-22 10:38 UTC
I have an effect that calls multiple effects using `run-waterfall`. The "sub" effects use the `choo/http` module to make an http request. When the requests encounter an error, they `return done('Bad request')`. This error message bubbles up to the parent effect, which calls `done(err)` itself, bubbling it up to the application event handler, which logs an uncaught error.

The problem is the uncaught error is being logged twice. [Here's a test case](http://requirebin.com/?gist=5a5b69a86a1a5fa41d16011886138b6a) to demonstrate. If you switch out the http call with the `setTimeout` call, it only logs once. Also if you comment out the `done(err)` in the parent effect, it only logs once.

Am I crazy or is this unexpected behaviour?

**Comment by yoshuawuyts** [comment] 2016-07-22 11:01
Can confirm, code looks good and behavior is def unexpected :/

**Comment by yoshuawuyts** [comment] 2016-07-22 11:04
aye, it seems `xhr` is calling its callback twice. Phew, not a bug in `wayfarer` at least. Think it'd be best to flag it there

**Comment by naugtur** [comment] 2016-07-22 13:14
fixed in v2.2.2

I'm curious, what is the purpose of throwing errors in an asynchronous callback from http request?

**Comment by yoshuawuyts** [comment] 2016-07-22 18:20
> I'm curious, what is the purpose of throwing errors in an asynchronous callback from http request?

The default error handler uses `throw` for errors, which can be changed to do something sensible, like displaying it in the UI and logging it or something (strongly recommended haha). Glad this error could be fixed, phewwwww. Thanks heaps for finding and fixing this @timwis @naugtur :grin: :sparkles:

**Closed by yoshuawuyts** 2016-07-22 18:20 UTC
